title                   : Home
name                    : Duncan Wentzel
include: ["_pages"]

# Site Author
author:
  name                  : "Duncan Wentzel"
  avatar                : /assets/images/bio-photo.jpeg
  bio                   : ""
  location              : "Huntingdon, PA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:yourname@email.com"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/duncan-wentzel-5605081b6/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/wentzel_designs/"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:yourname@email.com"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/duncan-wentzel-5605081b6/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/wentzel_designs/"

baseurl: "/duncan-site" # the subpath of your site, e.g. /blog
url: "https://jdy4k.github.io" # the base hostname & protocol for your site

# GitHub Pages repository
repository: jdy4k/duncan-site

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "nord"
enable_darkmode: true
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

sass:
  style: compressed
